[package]
name = "smol"
version = "1.2.4"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "A small and fast async runtime"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stjepang/smol"
homepage = "https://github.com/stjepang/smol"
documentation = "https://docs.rs/smol"
keywords = ["async", "await", "future", "io", "networking"]
categories = ["asynchronous", "concurrency", "network-programming"]
readme = "README.md"

[dependencies]
async-channel = "1.4.2"
async-executor = "1.1.0"
async-fs = "1.3.0"
async-io = "1.1.2"
async-lock = "2.3.0"
async-net = "1.4.3"
async-process = "1.0.0"
blocking = "1.0.0"
futures-lite = "1.11.0"
once_cell = "1.4.1"

[dev-dependencies]
anyhow = "1.0.32"
async-dup = "1.2.2"
async-h1 = "2.1.2"
async-native-tls = "0.3.3"
async-std = "1.6.4"
async-tungstenite = { version = "0.8.0", features = ["async-native-tls"] }
base64 = "0.12.3"
ctrlc = "3.1.6"
doc-comment = "0.3.3"
futures = "0.3.5"
http = "0.2.1"
http-types = "2.4.0"
hyper = { version = "0.13.8", default-features = false, features = ["stream"] }
native-tls = "0.2.4"
num_cpus = "1.13.0"
scraper = "0.12.0"
signal-hook = "0.1.16"
surf = { version = "2.0.0-alpha.5", default-features = false, features = ["h1-client"] }
tempfile = "3.1.0"
tide = "0.13.0"
tokio = { version = "0.2.22", default-features = false, features = ["rt-threaded"] }
tungstenite = "0.11.1"
url = "2.1.1"

[target.'cfg(target_os = "linux")'.dev-dependencies]
inotify = { version = "0.8.3", default-features = false }
nix = "0.18.0"
timerfd = "1.1.1"

[target.'cfg(windows)'.dev-dependencies]
uds_windows = "0.1.5"
